### ISSUE TITLE
Failed to activate the atom-zeal package

### ISSUE THREAD

**Issue by despairblue** [gliwka/atom-zeal#10]
[Enter steps to reproduce below:]

Happens when opening atom 0.206.0

**Atom Version**: 0.206.0
**System**: linux 3.14.43-2-lts
**Thrown From**: [atom-zeal](https://github.com/gliwka/atom-zeal) package, v0.1.0

### Stack Trace

Failed to activate the atom-zeal package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/home/despairblue/.atom/packages/atom-zeal/lib/atom-zeal.coffee:10:25)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
    at /usr/share/atom/resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:451:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:435:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:430:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:411:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:636:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop",
      "navigate",
      "markdown-scroll-sync"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true,
    "ignoredNames": [
      "SCENE"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
atom-fuzzy-grep, v0.2.0
atom-ternjs, v0.6.4
atom-zeal, v0.1.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.0
color-picker, v2.0.4
compare-files, v0.4.1
docblockr, v0.7.2
editorconfig, v1.0.0
file-icons, v1.5.7
git-log, v0.4.1
go-plus, v3.3.11
grammar-token-limit, v0.1.1
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dockerfile, v0.1.0
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.12.0
language-tss, v0.4.0
latex, v0.24.1
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-htmlhint, v0.0.16
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.8
notifications, v0.49.0
package-sync, v0.2.0
pdf-view, v0.22.0
project-manager, v1.15.8
react, v0.12.0
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by gliwka** [comment]
Thanks a lot, it's now fixed with v0.1.2
